name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        # optionally set specific poetry version. Defaults to latest
        uses: Gr1N/setup-poetry@v8
      - name: Install dependencies with Poetry
        # poetry setuptools workaround sourced from:
        # https://github.com/python-poetry/poetry/issues/7611#issuecomment-1711443539
        run: |
          poetry --version
          poetry self add setuptools
          poetry install

          # Install twine to test build
          python -m pip install build twine
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Build docs
        run: |
          cd docs && poetry run make html && cd ..
      - name: Test syntax of build package
        run: |
          python -m build
          python -m twine check dist/*
      - name: Run pytest
        run: poetry run pytest -v --cov-report term-missing --cov
      - name: Coveralls
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run coveralls --service=github
